spring:
  datasource:
    url: jdbc:h2:file:~/db/incubasecurity
    username: sa
    password:
  jpa:
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
